plugins {
  id 'java'
  id "org.kie.kogito.gradle" version "${kogitoPluginVersion}"
  id "org.springframework.boot" version "${springBootVersion}"
}

group = 'org.acme' // TODO: CHANGE THIS
version = '1.0.0-SNAPSHOT' // TODO: CHANGE THIS

dependencies {
  /* Spring Boot BOM */
  implementation enforcedPlatform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")

  /* The BAMOE BOM manages all dependencies required to create */
  /* Business Services — including Apache KIE, Drools, jBPM, and Kogito */
  implementation platform("com.ibm.bamoe:bamoe-bom:${bamoeVersion}")

  /* BAMOE ILMT */
  /* Uncomment for non-containerized deployments only */
  // implementation 'com.ibm.bamoe:bamoe-ilmt-compliance-spring-boot-pamoe'

  /* Kogito Core */
  implementation 'org.jbpm:jbpm-with-drools-spring-boot-starter'
  implementation 'org.kie:kie-addons-springboot-process-management'
  implementation 'org.kie:kie-addons-springboot-process-svg'
  implementation 'org.kie:kie-addons-springboot-source-files'

  /* Kogito Persistance */
  implementation 'org.kie:kie-addons-springboot-persistence-jdbc'
  implementation 'org.springframework.boot:spring-boot-starter-jdbc'
  implementation 'org.postgresql:postgresql'
  implementation 'org.flywaydb:flyway-database-postgresql'

  /* Kogito Data-Index */
  implementation 'org.kie:kogito-addons-springboot-data-index-jpa'

  /* Kogito Data-Audit */
  implementation 'org.kie:kogito-addons-springboot-data-audit'
  implementation 'org.kie:kogito-addons-springboot-data-audit-jpa'

  /* Kogito Jobs Service */
  implementation 'org.kie:kogito-addons-springboot-embedded-jobs'
  implementation 'org.kie:kogito-addons-springboot-embedded-jobs-jpa'
  
  /* Kogito User Tasks persistence */
  implementation 'org.jbpm:jbpm-addons-springboot-usertask-storage-jpa'

  /* Kogito + Quarkus Event-driven Workflows */
  /* Uncomment when working with Message Events in BPMN */
  /* + application.properties # Event-driven Workflows # section */
  // implementation 'org.kie:kie-addons-springboot-messaging'
  // implementation 'org.springframework.kafka:spring-kafka'

  /* BAMOE Spring Boot IdP Discovery addon */
  implementation 'com.ibm.bamoe:bamoe-spring-boot-idp-discovery'

  /* BAMOE Gen AI Task addon */
  implementation 'com.ibm.bamoe:bamoe-gen-ai-task-work-item-handler-spring-boot'

  /* BAMOE AI Agent Task addon */
  implementation 'com.ibm.bamoe:bamoe-ai-agent-task-work-item-handler-spring-boot'

  /* BAMOE Process Instance Migration (PIM) */
  implementation 'com.ibm.bamoe:bamoe-addons-spring-boot-pim'

  /* Spring Boot */
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  developmentOnly "org.springframework.boot:spring-boot-devtools:${springBootVersion}"

  /* Spring Boot Security */
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

  /* Testing */
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'io.rest-assured:rest-assured'

  // Required because of https://docs.junit.org/6.0.0/running-tests/build-support.html
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  
  /* Kogito Testing */
  testImplementation 'org.kie.kogito:kogito-scenario-simulation'
}

compileJava {
  options.encoding = 'UTF-8'
  options.compilerArgs << '-parameters'
}

compileTestJava {
  options.encoding = 'UTF-8'
}

/* the Main Class should point to your Spring Boot Application */
/* Entrypoint's bean (marked with @SpringBootApplication)      */
springBoot {
  mainClass = 'org.acme.BamoeSpringBootApplication'
}

/* Profiles Management */
/* To execute a build based on a profile, use ./gradlew clean build -PbuildProfile=dev */
/* You can add new profile using this pattern: */
/* 1. Create the `profile-{profileId}` in the project root */
/* 2. Execute it with ./gradlew clean build -PbuildProfile=profileId */
def profile = (findProperty('buildProfile') ?: '').toString()
if (profile) {
    apply from: "profile-${profile}.gradle"
}

/** DO NOT EDIT / REMOVE BELOW DECLARATIONS **/
/* Those steps are REQUIRED to correctly build this Business Services project */
tasks.named("resolveMainClassName") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootRun") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootJar") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("jar") {
  dependsOn(tasks.named("compileSecondaryJava"))
  from(tasks.named("compileSecondaryJava").get())
}

tasks.named("compileTestJava") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

generateModelConfig {
  jsonSchemaVersion = "DRAFT_2019_09"
}

test {
  dependsOn(tasks.named("compileSecondaryJava"))
  // Required because of https://docs.junit.org/6.0.0/running-tests/build-support.html
  useJUnitPlatform()
  // Preventing the build to fail with no tests (can be removed, once tests are available)
  failOnNoDiscoveredTests = false
}