quarkus.kogito.devservices.enabled=false
quarkus.devservices.enabled=false

###################
# Security :: Dev #
###################

%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=*
# This parameter accepts a list of hosts OR a regex that matches the host of an URL
# The Regex matches the 'host' part of an URL, everything from the beginning until the first forward slash
# e.g. for "dev-deployment-y0gy8a2810.apps.rm2.thpm.p1.openshiftapps.com/q/dev-ui" it will match "dev-deployment-y0gy8a2810.apps.rm2.thpm.p1.openshiftapps.com"
%dev.quarkus.dev-ui.hosts=^([^/]+)*(/.+)?$